# Set your theme here
theme = "hugo-tufte"
# The language of your website (see https://www.andiamo.co.uk/resources/iso-language-codes/ for reference)
languageCode = "en-us"
# The url of your website
baseurl = ""
# The title of your website (shown on all the pages)
title = "Bagsy"
# Site wide kill switch for Latex support
math = true
# (If math is enabled) 
## if "katex" is set to true katex will be used to render LaTex, if not MathJax will be used instead
katex = true

[params]
  # Subtitle of the website
  #subtitle = "Subtitle goes here."
  # Your name or the name of you company
  #copyrightHolder = "Copyright Holder"
  # Show the "Powered by Hugo-Tufte and Hugo." 
  showPoweredBy = true
  # Site wide kill switch
  hidedate = false
  # Uncomment for dark code blocks
  # codeBlocksDark = true
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fas fa-home la-lg'></i>"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fas fa-pen fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-tags fa-lg'></i> "
  weight = -90 
  identifier = "categories"
  url = "/about"
[[menu.nav]]
  name = "Bookshelf"
  pre = "<i class='fas fa-book  fa-lg'></i> "
  weight = -80 
  identifier = "books"
  url = "/books"

# -----------------------------------------------------------------------
# FOOTER MENU
# If you need to add custom links to you footer: put them here. Be aware that this theme is using fontawesome. 
# Please head to https://fontawesome.com/v4.7/icons/ to pick icons
# -----------------------------------------------------------------------

# Don't change the settings below
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true
